# Generated by Django 2.2.4 on 2019-10-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191013_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('working_with_author', 'Work with authors'),)},
        ),
    ]
